package ERS_NU;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;


import javax.swing.JOptionPane;

public class ContactInfo extends javax.swing.JFrame {
    
    private String name;
    private String studentid;
    private String phone;
    private String email;
   
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ContactInfo.class.getName());

    /**
     * Creates new form ContactInfo
     */
    public ContactInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p1 = new javax.swing.JPanel();
        btncheckevents = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();
        p2 = new javax.swing.JPanel();
        lblname = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        lblstudentidno = new javax.swing.JLabel();
        txtstudentidno = new javax.swing.JTextField();
        lblphoneno = new javax.swing.JLabel();
        txtphoneno = new javax.swing.JTextField();
        lblemail = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        btnnext = new javax.swing.JButton();
        javax.swing.JLabel bulldog = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        btnlogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p1.setBackground(new java.awt.Color(31, 40, 108));
        p1.setToolTipText("");
        p1.setPreferredSize(new java.awt.Dimension(1000, 750));
        p1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncheckevents.setBackground(new java.awt.Color(255, 222, 89));
        btncheckevents.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btncheckevents.setText("CHECK AVAILABLE EVENTS");
        btncheckevents.setBorder(null);
        btncheckevents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncheckeventsActionPerformed(evt);
            }
        });
        p1.add(btncheckevents, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, 70));

        lbl1.setFont(new java.awt.Font("Serif", 0, 64)); // NOI18N
        lbl1.setForeground(new java.awt.Color(255, 255, 255));
        lbl1.setText("Contact");
        p1.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 67));

        p2.setOpaque(false);
        p2.setPreferredSize(new java.awt.Dimension(400, 450));
        p2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblname.setBackground(new java.awt.Color(255, 255, 255));
        lblname.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        lblname.setText("Student Name");
        p2.add(lblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        txtname.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        p2.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 388, 50));

        lblstudentidno.setBackground(new java.awt.Color(255, 255, 255));
        lblstudentidno.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        lblstudentidno.setText("Student ID Number");
        p2.add(lblstudentidno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));

        txtstudentidno.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        txtstudentidno.setPreferredSize(new java.awt.Dimension(64, 30));
        txtstudentidno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstudentidnoActionPerformed(evt);
            }
        });
        p2.add(txtstudentidno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 388, 50));

        lblphoneno.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        lblphoneno.setText("Phone Number");
        p2.add(lblphoneno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, -1));

        txtphoneno.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        txtphoneno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphonenoActionPerformed(evt);
            }
        });
        p2.add(txtphoneno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 388, 55));

        lblemail.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        lblemail.setText("Student Email");
        p2.add(lblemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, -1, -1));

        txtemail.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        p2.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 388, 55));

        btnnext.setBackground(new java.awt.Color(255, 222, 89));
        btnnext.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnnext.setText("NEXT");
        btnnext.setBorder(null);
        btnnext.setContentAreaFilled(false);
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });
        p2.add(btnnext, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 420, 60));

        p1.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 440, 530));

        bulldog.setBackground(new java.awt.Color(0, 0, 102));
        bulldog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/r/s/nu/Pictures and icons/buldgo.png"))); // NOI18N
        p1.add(bulldog, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 351, 290));

        lbl2.setFont(new java.awt.Font("Serif", 0, 64)); // NOI18N
        lbl2.setForeground(new java.awt.Color(255, 255, 255));
        lbl2.setText("Information");
        p1.add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 58));

        btnlogout.setBackground(new java.awt.Color(255, 222, 89));
        btnlogout.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/r/s/nu/Pictures and icons/logout 48 px.png"))); // NOI18N
        btnlogout.setText("LOGOUT");
        btnlogout.setBorder(null);
        btnlogout.setContentAreaFilled(false);
        btnlogout.setPreferredSize(new java.awt.Dimension(170, 55));
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        p1.add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 350, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/r/s/nu/Pictures and icons/figma_pics/500 560 rectangle with button forgot password.png"))); // NOI18N
        p1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 530, 570));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/r/s/nu/Pictures and icons/figma_pics/350 70 rectangle with curved sides.png"))); // NOI18N
        p1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/r/s/nu/Pictures and icons/figma_pics/350 70 rectangle with curved sides.png"))); // NOI18N
        p1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtphonenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphonenoActionPerformed
        // TODO add your handling code here:
        txtphoneno.getText();
    }//GEN-LAST:event_txtphonenoActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
    
        LOGIN login = new LOGIN();
        login.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
        txtname.getText();
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtstudentidnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstudentidnoActionPerformed
        // TODO add your handling code here:
        txtstudentidno.getText();
    }//GEN-LAST:event_txtstudentidnoActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
        txtemail.getText();
    }//GEN-LAST:event_txtemailActionPerformed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
        // TODO add your handling code here:
    String name = txtname.getText();
    String studentid = txtstudentidno.getText();
    String phone = txtphoneno.getText();
    String email = txtemail.getText();

    if(name.trim().isEmpty() || 
       studentid.trim().isEmpty() || 
       phone.trim().isEmpty() || 
       email.trim().isEmpty()) {

        javax.swing.JOptionPane.showMessageDialog(this,
        "There is no inputed data.",
        "Login Error.",
        javax.swing.JOptionPane.ERROR_MESSAGE);

    } else {

        // ipapasa yung contact info sa InputPage2
        InputPage2 Reserve = new InputPage2(
                name,
                studentid,
                phone,
                email
        );

        Reserve.setVisible(true);

        this.dispose();
        }
    }//GEN-LAST:event_btnnextActionPerformed

    private void btncheckeventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncheckeventsActionPerformed
        // TODO add your handling code here:
     UserCheckAvailability UCA = new UserCheckAvailability();
     UCA.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_btncheckeventsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ContactInfo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncheckevents;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnnext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblphoneno;
    private javax.swing.JLabel lblstudentidno;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtphoneno;
    private javax.swing.JTextField txtstudentidno;
    // End of variables declaration//GEN-END:variables

    }

