package ERS_NU;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.JFrame;

public class ContactInfo extends javax.swing.JFrame {
    
 private String venue, eventType;
    private java.sql.Timestamp sqlStart, sqlEnd;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ContactInfo.class.getName());
    
    // Static memory for text fields
    public static String savedName = "", savedStudentId = "", savedPhone = "", savedEmail = "";

    // calling page JFrame
    private JFrame previousPage;
    
    public ContactInfo() {
        initComponents();
        jPanel3.setVisible(false);
        
        
        
    }
    public ContactInfo(String venue, java.sql.Timestamp start, java.sql.Timestamp end, String eventType) {
        initComponents();
        this.venue = venue;
        this.sqlStart = start;
        this.sqlEnd = end;
        this.eventType = eventType;
        this.previousPage = previousPage; // Capture the exact calling window instance
       
        txtname.setText(savedName);
        txtstudentidno.setText(savedStudentId);
        txtphoneno.setText(savedPhone);
        txtemail.setText(savedEmail);
        jPanel3.setVisible(false);
    }
   
         //Setter method to link the calling InputPage2 instance.
     
    public void setPreviousPage(InputPage2 previousPage) {
        this.previousPage = previousPage;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblGuide = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        p2 = new javax.swing.JPanel();
        lblname = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        lblstudentidno = new javax.swing.JLabel();
        txtstudentidno = new javax.swing.JTextField();
        lblphoneno = new javax.swing.JLabel();
        txtphoneno = new javax.swing.JTextField();
        lblemail = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        btnnext = new javax.swing.JButton();
        btnguide = new javax.swing.JButton();
        javax.swing.JLabel bulldog = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnReturn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p1.setBackground(new java.awt.Color(31, 40, 108));
        p1.setToolTipText("");
        p1.setPreferredSize(new java.awt.Dimension(1000, 750));
        p1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setEnabled(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGuide.setFont(new java.awt.Font("Serif", 3, 30)); // NOI18N
        lblGuide.setText("     Contact Info Guide");
        lblGuide.setToolTipText("");
        jPanel3.add(lblGuide, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 340, 40));

        jLabel15.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("the official name of the organization.");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 40));

        jLabel16.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("user booking on behalf of a school club or committee, enter the ");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 40));

        jLabel18.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("2.) If the user is not registering as a student, in Student ID;  type ");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 40));

        jLabel20.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("4.) If the reserver is not registering as a student, in Student Emial; ");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 40));

        jLabel24.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("@students.nu-dasma.edu.ph at the end.");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, 40));

        jLabel26.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("1.) If the resever is booking his/her self, ask for full name. If  the ");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 40));

        jLabel21.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("reserver not gonna register as a student");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 40));

        jLabel17.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText(" 2025-0000000");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 40));

        jLabel30.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("3.) In Phone number, ask for the Organizer's Phone Number.  If  the  ");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 40));

        jLabel31.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("ask for name of organization, club, committee or faculty then add ");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, 40));

        p1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 440, 370));

        lbl1.setFont(new java.awt.Font("Serif", 0, 64)); // NOI18N
        lbl1.setForeground(new java.awt.Color(255, 255, 255));
        lbl1.setText("Contact");
        p1.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, 67));

        p2.setOpaque(false);
        p2.setPreferredSize(new java.awt.Dimension(400, 450));
        p2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblname.setBackground(new java.awt.Color(255, 255, 255));
        lblname.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        lblname.setText("Student/Organization Name");
        p2.add(lblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        txtname.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        p2.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 388, 50));

        lblstudentidno.setBackground(new java.awt.Color(255, 255, 255));
        lblstudentidno.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        lblstudentidno.setText("Student ID Number");
        p2.add(lblstudentidno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));

        txtstudentidno.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        txtstudentidno.setPreferredSize(new java.awt.Dimension(64, 30));
        txtstudentidno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstudentidnoActionPerformed(evt);
            }
        });
        p2.add(txtstudentidno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 388, 50));

        lblphoneno.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        lblphoneno.setText("Phone Number");
        p2.add(lblphoneno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        txtphoneno.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        txtphoneno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphonenoActionPerformed(evt);
            }
        });
        p2.add(txtphoneno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 388, 55));

        lblemail.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        lblemail.setText("Student Email");
        p2.add(lblemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, -1, -1));

        txtemail.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        p2.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 388, 55));

        btnnext.setBackground(new java.awt.Color(255, 222, 89));
        btnnext.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btnnext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/r/s/nu/Pictures and icons/confirm 48px.png"))); // NOI18N
        btnnext.setText("SUBMIT");
        btnnext.setBorder(null);
        btnnext.setContentAreaFilled(false);
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });
        p2.add(btnnext, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 420, 60));

        btnguide.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        btnguide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/r/s/nu/Pictures and icons/20 20 info logo.png"))); // NOI18N
        btnguide.setText("GUIDE");
        btnguide.setToolTipText("\"Please select your Venue and Date first!\"");
        btnguide.setBorder(null);
        btnguide.setBorderPainted(false);
        btnguide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnguideMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnguideMouseExited(evt);
            }
        });
        btnguide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguideActionPerformed(evt);
            }
        });
        p2.add(btnguide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 100, 30));

        p1.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 460, 530));

        bulldog.setBackground(new java.awt.Color(0, 0, 102));
        bulldog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/r/s/nu/Pictures and icons/buldgo.png"))); // NOI18N
        p1.add(bulldog, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 351, 290));

        lbl2.setFont(new java.awt.Font("Serif", 0, 64)); // NOI18N
        lbl2.setForeground(new java.awt.Color(255, 255, 255));
        lbl2.setText("Information");
        p1.add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, 58));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/r/s/nu/Pictures and icons/figma_pics/500 560 rectangle with button forgot password.png"))); // NOI18N
        p1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 530, 570));

        btnReturn.setBackground(new java.awt.Color(255, 222, 89));
        btnReturn.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        btnReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/r/s/nu/Pictures and icons/32 32 return png.png"))); // NOI18N
        btnReturn.setText("Return");
        btnReturn.setContentAreaFilled(false);
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        p1.add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 160, 60));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/r/s/nu/Pictures and icons/figma_pics/150 51 for return button.png"))); // NOI18N
        p1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 41, 160, 80));

        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtphonenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphonenoActionPerformed
        // TODO add your handling code here:
        txtphoneno.getText();
    }//GEN-LAST:event_txtphonenoActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
        txtname.getText();
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtstudentidnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstudentidnoActionPerformed
        // TODO add your handling code here:
        txtstudentidno.getText();
    }//GEN-LAST:event_txtstudentidnoActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
        txtemail.getText();
    }//GEN-LAST:event_txtemailActionPerformed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
        // TODO add your handling code here:
String name = txtname.getText().trim();
String studentid = txtstudentidno.getText().trim();
String phone = txtphoneno.getText().trim();
String email = txtemail.getText().trim();

if (name.isEmpty() || studentid.isEmpty() || phone.isEmpty() || email.isEmpty()) {
    JOptionPane.showMessageDialog(this,
            "Please fill in all details.",
            "Input Error",
            JOptionPane.ERROR_MESSAGE);
    return;
}

StringBuilder errorMessage = new StringBuilder();
boolean isValid = true;

// STUDENT ID VALIDATION
if (!studentid.matches("^20(2[1-9]|[3-9][0-9])-\\d{7}$")) {
    errorMessage.append("Student ID must be 2025-xxxxx (e.g. 2025-12345).\n");
    isValid = false;
}
// PHONE VALIDATION
if (!phone.matches("^09\\d{9}$")) {
    errorMessage.append("Phone must be 11 digits and start with 09.\n");
    isValid = false;
}
// NU EMAIL ONLY 
if (!email.matches("^[A-Za-z0-9._%+-]+@students\\.nu-dasma\\.edu\\.ph$")) {
    errorMessage.append("Email must be a valid NU email (example: name@students.nu-dasma.edu.ph).\n");
    isValid = false;
}

if (!isValid) {
    JOptionPane.showMessageDialog(this,
            errorMessage.toString(),
            "Validation Error",
            JOptionPane.ERROR_MESSAGE);
    return;
}
// CUSTOM EVENT ID GENERATOR & PASS TO OUTPUT 
String newEventCode = "";
int currentYear = LocalDate.now().getYear();

try {
    Connection conn = DBConnection.getConnection();
    // Ask the database for the highest Event Code from this specific year
    String sql = "SELECT Event_id FROM reservation_data WHERE Event_id LIKE ? ORDER BY Event_id DESC LIMIT 1";
    PreparedStatement pst = conn.prepareStatement(sql);
    pst.setString(1, currentYear + "-%"); 
    ResultSet rs = pst.executeQuery();

    if (rs.next()) {
        // If it finds one (e.g., "2026-0012"), extract the "12", add 1, and reformat it
        String lastId = rs.getString("Event_id"); 
        int sequence = Integer.parseInt(lastId.split("-")[1]); 
        sequence++; 
        newEventCode = currentYear + "-" + String.format("%04d", sequence); // Creates "2026-0013"
    } else {
        // If the database is empty for this year, start at 0001!
        newEventCode = currentYear + "-0001";
    }
    
    rs.close(); pst.close(); conn.close();

} catch (SQLException e) {
    JOptionPane.showMessageDialog(this, "Error generating Event Code: " + e.getMessage());
    return; 
}

// PASS ALL DATA TO OUTPUT PAGE (We are NOT saving to the database here)
String receiptDates = this.sqlStart + " TO " + this.sqlEnd;

output out = new output(newEventCode, studentid, email, phone, LOGIN.loggedInEmpID, this.venue, receiptDates, name, this.sqlStart, this.sqlEnd, this.eventType);
out.setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_btnnextActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        savedName = txtname.getText();
        savedStudentId = txtstudentidno.getText();
        savedPhone = txtphoneno.getText();
        savedEmail = txtemail.getText();

        if (previousPage != null) {
            previousPage.setVisible(true);
        } else {
            new InputPage2().setVisible(true); 
        }
        this.dispose();
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnguideMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnguideMouseEntered
        jPanel3.setVisible(true);
    }//GEN-LAST:event_btnguideMouseEntered

    private void btnguideMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnguideMouseExited
        jPanel3.setVisible(false);
    }//GEN-LAST:event_btnguideMouseExited
          
    
    private void btnguideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnguideActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ContactInfo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnguide;
    private javax.swing.JButton btnnext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lblGuide;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblphoneno;
    private javax.swing.JLabel lblstudentidno;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtphoneno;
    private javax.swing.JTextField txtstudentidno;
    // End of variables declaration//GEN-END:variables

    }
