

package ERS_NU;


public class Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnregister = new javax.swing.JButton();
        btnmanage = new javax.swing.JButton();
        btnlogin = new javax.swing.JButton();
        bgMD = new javax.swing.JLabel();
        bgMD1 = new javax.swing.JLabel();
        bgMD2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 750));
        jPanel1.setLayout(null);

        btnregister.setBackground(new java.awt.Color(255, 222, 89));
        btnregister.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        btnregister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/r/s/nu/Pictures and icons/add employee 48px.png"))); // NOI18N
        btnregister.setText("Register");
        btnregister.setBorder(null);
        btnregister.setContentAreaFilled(false);
        btnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnregister);
        btnregister.setBounds(40, 580, 300, 60);

        btnmanage.setBackground(new java.awt.Color(255, 222, 89));
        btnmanage.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        btnmanage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/r/s/nu/Pictures and icons/Manage.png"))); // NOI18N
        btnmanage.setText("Manage Data");
        btnmanage.setBorder(null);
        btnmanage.setContentAreaFilled(false);
        btnmanage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanageActionPerformed(evt);
            }
        });
        jPanel1.add(btnmanage);
        btnmanage.setBounds(350, 580, 350, 60);

        btnlogin.setBackground(new java.awt.Color(255, 222, 89));
        btnlogin.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        btnlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/r/s/nu/Pictures and icons/LOGIN.png"))); // NOI18N
        btnlogin.setText("LOGIN");
        btnlogin.setBorder(null);
        btnlogin.setContentAreaFilled(false);
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogin);
        btnlogin.setBounds(710, 580, 270, 60);

        bgMD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/r/s/nu/Pictures and icons/figma_pics/350 70 rectangle with curved sides.png"))); // NOI18N
        jPanel1.add(bgMD);
        bgMD.setBounds(60, 580, 280, 60);

        bgMD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/r/s/nu/Pictures and icons/figma_pics/350 70 rectangle with curved sides.png"))); // NOI18N
        jPanel1.add(bgMD1);
        bgMD1.setBounds(710, 580, 270, 60);

        bgMD2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/r/s/nu/Pictures and icons/figma_pics/350 70 rectangle with curved sides.png"))); // NOI18N
        jPanel1.add(bgMD2);
        bgMD2.setBounds(360, 580, 340, 60);

        jLabel7.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("A Reservation System that allows admin to efficiently");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(90, 210, 460, 40);

        jLabel1.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("National University - Dasmarinas.");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 250, 320, 40);

        jLabel3.setFont(new java.awt.Font("Serif", 0, 60)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 222, 89));
        jLabel3.setText("Campus Event");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 60, 440, 100);

        jLabel4.setFont(new java.awt.Font("Serif", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 222, 89));
        jLabel4.setText("Reservation System");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(100, 130, 400, 80);

        jLabel5.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("manage and organize campus events and place within");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(90, 230, 440, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/r/s/nu/Pictures and icons/Untitled design.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jLabel8.setPreferredSize(new java.awt.Dimension(1000, 750));
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 0, 1000, 760);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnmanageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanageActionPerformed
        Database data = new Database();
        data.setVisible(true);
        this.dispose();
    
    }//GEN-LAST:event_btnmanageActionPerformed

    private void btnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregisterActionPerformed
        Employee addEmployee = new Employee();
     addEmployee.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_btnregisterActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        LOGIN log = new LOGIN();
     log.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_btnloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgMD;
    private javax.swing.JLabel bgMD1;
    private javax.swing.JLabel bgMD2;
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnmanage;
    private javax.swing.JButton btnregister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
