
package ERS_NU;
public class output extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(output.class.getName());

    public output(String eventCode, String studentId, String studentEmail, String studentNumber, String employeeId, String venue, String startToEnd) {
        initComponents();
        
        // IMPORTANT: Change "lblStudentId", etc., to the exact variable names 
        // of those gray text boxes/labels on your output design!
        txtstudentid.setText(studentId);
        txtstudentemail.setText(studentEmail);
        txtstudentnum.setText(studentNumber);
        txtemployeeid.setText(employeeId);
        txtvenue.setText(venue);
        txtstartend.setText(startToEnd);
        txteventid.setText(eventCode);
    }
    
    public output() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelRecpt = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelNme = new javax.swing.JLabel();
        jLabelStud = new javax.swing.JLabel();
        jLabelVnue = new javax.swing.JLabel();
        jLabeldate = new javax.swing.JLabel();
        jLabelCode = new javax.swing.JLabel();
        txtstudentid = new javax.swing.JTextField();
        txtvenue = new javax.swing.JTextField();
        txtemployeeid = new javax.swing.JTextField();
        txteventid = new javax.swing.JTextField();
        txtstartend = new javax.swing.JTextField();
        jLabelVnue1 = new javax.swing.JLabel();
        jLabelVnue2 = new javax.swing.JLabel();
        txtstudentemail = new javax.swing.JTextField();
        txtstudentnum = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonLogout = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jButtonConfirm = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jTextField5.addActionListener(this::jTextField5ActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(31, 40, 108));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(31, 40, 108));
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 750));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelRecpt.setBackground(new java.awt.Color(31, 40, 108));
        jLabelRecpt.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jLabelRecpt.setForeground(new java.awt.Color(31, 40, 108));
        jLabelRecpt.setText("RESERVATION RECEIPT ");
        jPanel1.add(jLabelRecpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 465, 31));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 498, 31));

        jLabelNme.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabelNme.setForeground(new java.awt.Color(31, 40, 108));
        jLabelNme.setText("Student ID");
        jPanel1.add(jLabelNme, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 199, -1));

        jLabelStud.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabelStud.setForeground(new java.awt.Color(31, 40, 108));
        jLabelStud.setText("Employee ID");
        jPanel1.add(jLabelStud, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 199, -1));

        jLabelVnue.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabelVnue.setForeground(new java.awt.Color(31, 40, 108));
        jLabelVnue.setText("Student Number");
        jPanel1.add(jLabelVnue, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 199, -1));

        jLabeldate.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabeldate.setForeground(new java.awt.Color(31, 40, 108));
        jLabeldate.setText("Start to End");
        jPanel1.add(jLabeldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, -1, -1));

        jLabelCode.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabelCode.setForeground(new java.awt.Color(31, 40, 108));
        jLabelCode.setText("Event Code: ");
        jPanel1.add(jLabelCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, 142, -1));

        txtstudentid.setEditable(false);
        txtstudentid.setEnabled(false);
        txtstudentid.addActionListener(this::txtstudentidActionPerformed);
        jPanel1.add(txtstudentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 223, 30));

        txtvenue.setEditable(false);
        txtvenue.setEnabled(false);
        txtvenue.addActionListener(this::txtvenueActionPerformed);
        jPanel1.add(txtvenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 223, 30));

        txtemployeeid.setEditable(false);
        txtemployeeid.setEnabled(false);
        txtemployeeid.addActionListener(this::txtemployeeidActionPerformed);
        jPanel1.add(txtemployeeid, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 223, 30));

        txteventid.setEnabled(false);
        txteventid.addActionListener(this::txteventidActionPerformed);
        jPanel1.add(txteventid, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, 223, 30));

        txtstartend.setEditable(false);
        txtstartend.setEnabled(false);
        txtstartend.addActionListener(this::txtstartendActionPerformed);
        jPanel1.add(txtstartend, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 223, 30));

        jLabelVnue1.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabelVnue1.setForeground(new java.awt.Color(31, 40, 108));
        jLabelVnue1.setText("Venue        ");
        jPanel1.add(jLabelVnue1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 199, -1));

        jLabelVnue2.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabelVnue2.setForeground(new java.awt.Color(31, 40, 108));
        jLabelVnue2.setText("Student Email");
        jPanel1.add(jLabelVnue2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 199, -1));

        txtstudentemail.setEditable(false);
        txtstudentemail.setEnabled(false);
        txtstudentemail.addActionListener(this::txtstudentemailActionPerformed);
        jPanel1.add(txtstudentemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 223, 30));

        txtstudentnum.setEditable(false);
        txtstudentnum.setEnabled(false);
        txtstudentnum.addActionListener(this::txtstudentnumActionPerformed);
        jPanel1.add(txtstudentnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 223, 30));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 570, 660));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/r/s/nu/Pictures and icons/figma_pics/receipt 6 - 568 681.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        jButtonLogout.setBackground(new java.awt.Color(255, 222, 89));
        jButtonLogout.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jButtonLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/r/s/nu/Pictures and icons/logout 48 px.png"))); // NOI18N
        jButtonLogout.setText("LOGOUT");
        jButtonLogout.setBorder(null);
        jButtonLogout.setContentAreaFilled(false);
        jButtonLogout.addActionListener(this::jButtonLogoutActionPerformed);
        jPanel2.add(jButtonLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 590, 170, 120));

        jButtonBack.setBackground(new java.awt.Color(255, 222, 89));
        jButtonBack.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/r/s/nu/Pictures and icons/48 px.png"))); // NOI18N
        jButtonBack.setText("RETURN");
        jButtonBack.setBorder(null);
        jButtonBack.setContentAreaFilled(false);
        jButtonBack.addActionListener(this::jButtonBackActionPerformed);
        jPanel2.add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 170, 40));

        jButtonConfirm.setBackground(new java.awt.Color(255, 222, 89));
        jButtonConfirm.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jButtonConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/r/s/nu/Pictures and icons/confirm 48px.png"))); // NOI18N
        jButtonConfirm.setText("CONFRIM");
        jButtonConfirm.setBorder(null);
        jButtonConfirm.setContentAreaFilled(false);
        jButtonConfirm.addActionListener(this::jButtonConfirmActionPerformed);
        jPanel2.add(jButtonConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 500, 170, 120));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/r/s/nu/Pictures and icons/figma_pics/2nd biggest 231 70 btn.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 20, 210, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/r/s/nu/Pictures and icons/figma_pics/2nd biggest 231 70 btn.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 490, 240, 140));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/r/s/nu/Pictures and icons/figma_pics/2nd biggest 231 70 btn.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 590, -1, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtvenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvenueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvenueActionPerformed

    private void txtemployeeidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemployeeidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemployeeidActionPerformed

    private void txteventidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txteventidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txteventidActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void txtstartendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstartendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstartendActionPerformed

    private void txtstudentidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstudentidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstudentidActionPerformed

    private void jButtonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmActionPerformed
        Database data = new Database();
        data.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonConfirmActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        Dashboard DasB = new Dashboard();
        DasB.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        InputPage2 Input = new InputPage2();
        Input.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void txtstudentemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstudentemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstudentemailActionPerformed

    private void txtstudentnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstudentnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstudentnumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new output().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonConfirm;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCode;
    private javax.swing.JLabel jLabelNme;
    private javax.swing.JLabel jLabelRecpt;
    private javax.swing.JLabel jLabelStud;
    private javax.swing.JLabel jLabelVnue;
    private javax.swing.JLabel jLabelVnue1;
    private javax.swing.JLabel jLabelVnue2;
    private javax.swing.JLabel jLabeldate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField txtemployeeid;
    private javax.swing.JTextField txteventid;
    private javax.swing.JTextField txtstartend;
    private javax.swing.JTextField txtstudentemail;
    private javax.swing.JTextField txtstudentid;
    private javax.swing.JTextField txtstudentnum;
    private javax.swing.JTextField txtvenue;
    // End of variables declaration//GEN-END:variables
}
