
package ERS_NU;
public class output extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(output.class.getName());


    public output() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelRecpt = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelNme = new javax.swing.JLabel();
        jLabelStud = new javax.swing.JLabel();
        jLabelVnue = new javax.swing.JLabel();
        jLabeldate = new javax.swing.JLabel();
        jLabelCode = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButtonLogout = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jButtonConfirm = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jTextField5.addActionListener(this::jTextField5ActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(31, 40, 108));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(31, 40, 108));
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 750));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelRecpt.setBackground(new java.awt.Color(31, 40, 108));
        jLabelRecpt.setFont(new java.awt.Font("Lucida Fax", 1, 36)); // NOI18N
        jLabelRecpt.setForeground(new java.awt.Color(31, 40, 108));
        jLabelRecpt.setText("RESERVATION RECEIPT ");
        jPanel1.add(jLabelRecpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 29, 465, 31));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 78, 498, 31));

        jLabelNme.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabelNme.setForeground(new java.awt.Color(31, 40, 108));
        jLabelNme.setText("Full Name            ");
        jPanel1.add(jLabelNme, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 199, -1));

        jLabelStud.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabelStud.setForeground(new java.awt.Color(31, 40, 108));
        jLabelStud.setText("Student ID     ");
        jPanel1.add(jLabelStud, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 199, -1));

        jLabelVnue.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabelVnue.setForeground(new java.awt.Color(31, 40, 108));
        jLabelVnue.setText("Venue        ");
        jPanel1.add(jLabelVnue, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 199, -1));

        jLabeldate.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabeldate.setForeground(new java.awt.Color(31, 40, 108));
        jLabeldate.setText("Date and Time      ");
        jPanel1.add(jLabeldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabelCode.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabelCode.setForeground(new java.awt.Color(31, 40, 108));
        jLabelCode.setText("Event Code: ");
        jPanel1.add(jLabelCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 142, -1));

        jTextField1.setEditable(false);
        jTextField1.setEnabled(false);
        jTextField1.addActionListener(this::jTextField1ActionPerformed);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 223, 30));

        jTextField2.setEditable(false);
        jTextField2.setEnabled(false);
        jTextField2.addActionListener(this::jTextField2ActionPerformed);
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 223, 30));

        jTextField3.setEditable(false);
        jTextField3.setEnabled(false);
        jTextField3.addActionListener(this::jTextField3ActionPerformed);
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 223, 30));

        jTextField4.setEnabled(false);
        jTextField4.addActionListener(this::jTextField4ActionPerformed);
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 223, 30));

        jTextField6.setEditable(false);
        jTextField6.setEnabled(false);
        jTextField6.addActionListener(this::jTextField6ActionPerformed);
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 223, 30));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 550, 520));

        jButtonLogout.setBackground(new java.awt.Color(255, 222, 89));
        jButtonLogout.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jButtonLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/r/s/nu/Pictures and icons/logout 48 px.png"))); // NOI18N
        jButtonLogout.setText("LOGOUT");
        jButtonLogout.setBorder(null);
        jButtonLogout.setContentAreaFilled(false);
        jButtonLogout.addActionListener(this::jButtonLogoutActionPerformed);
        jPanel2.add(jButtonLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 490, 170, 70));

        jButtonBack.setBackground(new java.awt.Color(255, 222, 89));
        jButtonBack.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/r/s/nu/Pictures and icons/48 px.png"))); // NOI18N
        jButtonBack.setText("BACK");
        jButtonBack.setBorder(null);
        jButtonBack.setContentAreaFilled(false);
        jButtonBack.addActionListener(this::jButtonBackActionPerformed);
        jPanel2.add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 590, 170, 70));

        jButtonConfirm.setBackground(new java.awt.Color(255, 222, 89));
        jButtonConfirm.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jButtonConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/r/s/nu/Pictures and icons/confirm 48px.png"))); // NOI18N
        jButtonConfirm.setText("CONFRIM");
        jButtonConfirm.setBorder(null);
        jButtonConfirm.setContentAreaFilled(false);
        jButtonConfirm.addActionListener(this::jButtonConfirmActionPerformed);
        jPanel2.add(jButtonConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 170, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/r/s/nu/Pictures and icons/figma_pics/Receipt 568 703.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, -10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/r/s/nu/Pictures and icons/figma_pics/170 70 rectangle half of the long button.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 590, 170, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/r/s/nu/Pictures and icons/figma_pics/170 70 rectangle half of the long button.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 240, 90));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/e/r/s/nu/Pictures and icons/figma_pics/170 70 rectangle half of the long button.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 490, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButtonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConfirmActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new output().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonConfirm;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCode;
    private javax.swing.JLabel jLabelNme;
    private javax.swing.JLabel jLabelRecpt;
    private javax.swing.JLabel jLabelStud;
    private javax.swing.JLabel jLabelVnue;
    private javax.swing.JLabel jLabeldate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
